In [3]:
import torch
from ALBERT import ALBERT

device = torch.device('mps' if torch.backends.mps.is_available() else "cpu")
input_ids = torch.randint(0,29999,(3,10))

In [12]:
input_ids = input_ids.to(device)

segment_ids = torch.IntTensor([[1]*10,[1]*5 +[2]*5, [2]*10]).to(device)
input_mask = torch.BoolTensor([[0]*10, [0]*5 +[1]*5, [1] * 10]).to(device)

print(input_ids.shape)
print(segment_ids.shape)
print(input_mask.shape)
print("=="*50)
print(input_ids)
print(segment_ids)
print(input_mask)

torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
tensor([[ 2937, 24934,  3147, 20548,  7542,  1131, 28324, 21396, 12708, 11377],
        [14902, 25179, 26533, 24678,   180,  8850, 23042, 19401, 19650,  8415],
        [ 3691, 10781, 23233,  2325, 18618,   521, 11853, 18761, 12247, 28269]],
       device='mps:0')
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], device='mps:0', dtype=torch.int32)
tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True]],
       device='mps:0')


In [14]:
albert_test = ALBERT(vocab_size=30000)
albert_test.to(device)
result = albert_test(input_ids,segment_ids,mask=input_mask)

In [15]:
print(result.shape)

torch.Size([3, 10, 768])


In [16]:
result[0:]

tensor([[[ 2.4671,  0.1909, -0.0435,  ...,  0.3825,  0.8484, -0.2222],
         [ 0.0000,  0.1984,  0.7001,  ...,  0.2878,  1.6756, -0.3367],
         [ 0.6444,  1.0998,  0.1340,  ...,  1.2334,  0.6162, -0.0000],
         ...,
         [ 1.0147, -0.3360,  0.9690,  ...,  0.9040,  1.6471, -0.2211],
         [ 1.7698,  0.6789, -0.3571,  ...,  1.1214,  1.2900, -0.3859],
         [ 2.3347,  1.1737,  0.0000,  ...,  1.2916,  0.0000, -0.0877]],

        [[ 0.8791, -1.1332,  0.5328,  ...,  1.1513,  1.1676, -0.1885],
         [ 2.1402, -0.5334,  0.0000,  ...,  0.0758,  1.8289,  0.1297],
         [ 0.6398, -0.8256,  0.0000,  ...,  0.6134,  3.8966,  0.7533],
         ...,
         [ 1.3614, -0.2157,  0.0049,  ...,  0.3635,  1.6792,  1.1353],
         [ 1.4331, -1.0871,  0.5986,  ...,  0.1337,  2.5710,  0.2612],
         [ 0.7978,  0.3364,  1.1188,  ...,  0.1144,  2.6503,  0.3094]],

        [[ 3.5548,  0.4170, -0.1092,  ..., -0.2692,  1.7388, -0.7333],
         [ 2.7976,  0.8087,  0.7484,  ...,  0

In [22]:
import torch
x = torch.tensor([2.],requires_grad=True).to(device)
y = x ** 2
print(y.grad.save)

/Users/jh/opt/anaconda3/envs/M1GPU/lib/python3.8/site-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:482.)
  return self._grad


AttributeError: 'NoneType' object has no attribute 'save'

In [41]:
input = torch.randn((1,1,4,4))
print(input.shape)

torch.Size([1, 1, 4, 4])


In [44]:
m = torch.nn.ConvTranspose2d(16,33,3,stride=2)
m

ConvTranspose2d(16, 33, kernel_size=(3, 3), stride=(2, 2))